default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: aidah_manaar_development

test:
  <<: *default
  database: aidah_manaar_test

production:
  <<: *default
  database: aidah_manaar_production
